name: Generate podcast feed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Feed Generator
        uses: sagar-neupane0/test-podcast-generator@main
